# Site Information
site_name: Gary Innerarity
site_description: Gary Innerarity (OSPF2FULLSTACK).
site_author: Gary Innerarity
site_url: https://garyinnerarity.com

# Configuration
docs_dir: docs

theme:
  name: material
  logo: ../assets/img/gary.jpg
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest

# Plugins
plugins: 
  - search:
      lang: en
  - minify:
      minify_html: true

# Navigation
nav:
  - Home: index.md
  - AWS: 
    - "aws/AWS-IoT.md"
  - Notion:
    - "notion/notion-ai.md"