# Site Information
site_name: Gary Innerarity
site_description: Gary Innerarity (OSPF2FULLSTACK).
site_author: Gary Innerarity
site_url: https://garyinnerarity.com

# Configuration
docs_dir: docs

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  logo: ../assets/img/gary.jpg
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      <type>: material/sticker-alert
  language: en
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
  

# Plugins
plugins: 
  - search:
      lang: en
  - minify:
      minify_html: true


# Extensions
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes

# language support
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Italian
      link: /it/
      lang: it
    - name: Korean
      link: /ko/
      lang: ko
    - name: Polish
      link: /pl/
      lang: pl
    - name: Romainian
      link: /ro/
      lang: ro
    - name: Dutch
      link: /nl/
      lang: nl
    - name: French
      link: /fr/
      lang: fr
    - name: German
      link: /de/
      lang: de
    - name: Hindi
      link: /hi/
      lang: hi
    - name: Spanish
      link: /es/
      lang: es

# Navigation
nav:
  - Home: index.md
  - Challenges:
    - 100 Days:
      - "100_days/100days_devops.md"
    - Cloud Resume Challege:
      - "cloud_resume/cloud_resume_challenge.md"
  - DevOps Tools:
    - "devops/devops_tools.md"
    - "gitlab/gitlab.md"
  - AWS: 
    - "aws/AWS-IoT.md"
  - Hardware:
    - "hardware/compute_blade/compute_blade.md"
    - "hardware/raspberry_pi/raspberry_pi.md"
    - "hardware/sparkfun/micromod.md"
  - Notion:
    - "notion/notion-ai.md"
  - Terraform:
    - "terraform/main(tf).md"


