# Site Information
site_name: Gary Innerarity
site_description: Gary Innerarity (OSPF2FULLSTACK).
site_author: Gary Innerarity
site_url: https://garyinnerarity.com

# Configuration
docs_dir: docs

theme:
  name: material
  logo: ../assets/img/gary.jpg
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      <type>: material/sticker-alert
  language: en
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
  

# Plugins
plugins: 
  - search:
      lang: en
  - minify:
      minify_html: true

# Navigation
nav:
  - Home: index.md
  - Challenges:
    - 100 Days:
      - "100_days/100days_devops.md"
    - Cloud Resume Challege:
      - "cloud_resume/cloud_resume_challenge.md"
  - DevOps Tools:
    - "devops/devops_tools.md"
    - "gitlab/gitlab.md"
  - AWS: 
    - "aws/AWS-IoT.md"
  - Hardware:
    - "hardware/compute_blade/compute_blade.md"
    - "hardware/raspberry_pi/raspberry_pi.md"
    - "hardware/sparkfun/micromod.md"
  - Notion:
    - "notion/notion-ai.md"
  - Terraform:
    - "terraform/main(tf).md"


# Extensions
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes